"use strict";
const PROJECT = "https://xbciyctqkwokpxlvxiro.supabase.co";
const PUBLIC_KEY = "sb_publishable_mMRYahDfhiPXDcj-Ui-0dg_LK0NR5-q";
const $ = id => document.getElementById(id);
let token=null, epoch=0, requestId=0, detailRequest=0, active={}, snapshot=null, cursors=[""], pageIndex=0, currentRows=[], total=0, detailId=null, kind="assessments", offset=0, exporting=false;
const timeFormat=new Intl.DateTimeFormat("th-TH",{timeZone:"Asia/Bangkok",dateStyle:"medium",timeStyle:"short"});
function time(value){return value?timeFormat.format(new Date(value)):"—";}
function cell(row,value){const td=document.createElement("td");td.textContent=value??"—";row.append(td);return td;}
function clearSession(){token=null;epoch++;requestId++;detailRequest++;$("dashboard").hidden=true;$("loginPanel").hidden=false;$("logout").hidden=true;$("rows").replaceChildren();$("historyRows").replaceChildren();$("detail").hidden=true;$("password").value="";currentRows=[];snapshot=null;}
async function jsonFetch(url, options){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),30000);try{const r=await fetch(url,{...options,signal:controller.signal});let data;try{data=await r.json();}catch{throw Error("ระบบตอบกลับไม่ถูกต้อง (HTTP "+r.status+")");}return {r,data};}finally{clearTimeout(timer);}}
async function api(body){const myEpoch=epoch;const {r,data}=await jsonFetch(PROJECT+"/functions/v1/admin-api",{method:"POST",headers:{"Content-Type":"application/json",apikey:PUBLIC_KEY,Authorization:"Bearer "+token},body:JSON.stringify(body)});if(myEpoch!==epoch)throw Error("การทำงานถูกยกเลิก");if(!r.ok){if(r.status===401||r.status===403){clearSession();$("loginError").textContent=data.error||"กรุณาเข้าสู่ระบบใหม่";}throw Error(data.error||"HTTP "+r.status);}return data;}
$("loginForm").addEventListener("submit",async e=>{e.preventDefault();$("loginButton").disabled=true;$("loginError").textContent="กำลังตรวจสอบสิทธิ์…";try{const {r,data}=await jsonFetch(PROJECT+"/auth/v1/token?grant_type=password",{method:"POST",headers:{"Content-Type":"application/json",apikey:PUBLIC_KEY},body:JSON.stringify({email:$("email").value.trim(),password:$("password").value})});$("password").value="";if(!r.ok||!data.access_token){
 const code=String(data.error_code||data.code||data.error||"unknown");
 const messages={invalid_credentials:"อีเมลหรือรหัสผ่านของบัญชี Authentication ไม่ตรง",email_not_confirmed:"บัญชียังไม่ยืนยันอีเมล",email_provider_disabled:"การเข้าสู่ระบบด้วยอีเมลถูกปิด",signup_disabled:"การสมัครบัญชีถูกปิด",over_request_rate_limit:"มีการลองเข้าสู่ระบบถี่เกินไป กรุณารอก่อนลองใหม่",user_banned:"บัญชีถูกระงับการใช้งาน"};
 const rawMessage=String(data.msg||data.message||data.error_description||"");
 const message=messages[code] || (/invalid api key/i.test(rawMessage)?"Publishable key ไม่ถูกต้องหรือไม่ตรงโครงการ": "Supabase ปฏิเสธการเข้าสู่ระบบ โปรดส่งรหัสข้อผิดพลาดนี้ให้ตรวจสอบ");
 throw Error("HTTP "+r.status+" · "+code+"\n"+message);
}token=data.access_token;epoch++;await api({action:"session"});$("loginPanel").hidden=true;$("dashboard").hidden=false;$("logout").hidden=false;$("loginError").textContent="";await resetReport();}catch(err){if(!$("loginPanel").hidden)token=null;$("loginError").textContent=err.name==="AbortError"?"ระบบตอบกลับช้า กรุณาลองใหม่":err.message;}finally{$("loginButton").disabled=false;}});
$("logout").addEventListener("click",()=>{const old=token;clearSession();$("loginError").textContent="ออกจากระบบแล้ว";if(old)void fetch(PROJECT+"/auth/v1/logout?scope=local",{method:"POST",headers:{apikey:PUBLIC_KEY,Authorization:"Bearer "+old}}).catch(()=>{});});
function filters(){const from=$("from").value,to=$("to").value;if(from&&to&&from>to)throw Error("วันเริ่มต้นต้องไม่อยู่หลังวันสิ้นสุด");return {from,to,query:$("query").value.trim()};}
async function resetReport(){try{active=filters();cursors=[""];pageIndex=0;snapshot=null;detailRequest++;$("detail").hidden=true;await loadReport();}catch(e){$("status").textContent=e.message;}}
async function loadReport(){const seq=++requestId;$("status").textContent="กำลังอ่านข้อมูล…";$("apply").disabled=true;$("prev").disabled=true;$("next").disabled=true;$("export").disabled=true;try{const data=await api({action:"summary",...active,snapshot,after:cursors[pageIndex]});if(seq!==requestId)return;snapshot=data.snapshot;currentRows=data.rows;total=Number(data.total_participants);$("people").textContent=total.toLocaleString("th-TH");$("assessments").textContent=Number(data.total_assessments).toLocaleString("th-TH");$("activities").textContent=Number(data.total_activity_opens).toLocaleString("th-TH");$("rows").replaceChildren();for(const item of currentRows){const row=document.createElement("tr"),td=document.createElement("td"),button=document.createElement("button");button.className="id-button";button.textContent=item.participant_id;button.addEventListener("click",()=>openDetail(item.participant_id));td.append(button);row.append(td);cell(row,item.assessment_count);cell(row,item.activity_count);cell(row,item.latest_score);cell(row,item.latest_level);cell(row,time(item.last_used_at));$("rows").append(row);}if(!currentRows.length){const row=document.createElement("tr");const td=cell(row,"ไม่พบข้อมูลตามเงื่อนไข");td.colSpan=6;$("rows").append(row);}$("scope").textContent="ช่วงข้อมูล: "+(active.from||"ทั้งหมด")+" ถึง "+(active.to||"ปัจจุบัน")+" · คะแนนล่าสุดอยู่ในช่วงนี้ · กิจกรรมนับเฉพาะการกดเปิด";$("page").textContent="หน้า "+(pageIndex+1)+" · "+total.toLocaleString("th-TH")+" รหัส";$("status").textContent="";$("prev").disabled=pageIndex===0;$("next").disabled=(pageIndex*100+currentRows.length)>=total;$("export").disabled=exporting||!total;}catch(e){if(seq===requestId){$("rows").replaceChildren();currentRows=[];$("people").textContent=$("assessments").textContent=$("activities").textContent="—";$("status").textContent=e.message;}}finally{if(seq===requestId)$("apply").disabled=false;}}
$("filters").addEventListener("submit",e=>{e.preventDefault();void resetReport();});
$("prev").onclick=()=>{if(pageIndex>0){pageIndex--;void loadReport();}};
$("next").onclick=()=>{if(currentRows.length){cursors[pageIndex+1]=currentRows.at(-1).participant_id;pageIndex++;void loadReport();}};
function csvCell(v){let s=String(v??"");if(/^[\s]*[=+@\-]/.test(s)||/^[\t\r\n]/.test(s))s="'"+s;return '"'+s.replaceAll('"','""')+'"';}
$("export").onclick=async()=>{if(exporting)return;exporting=true;$("export").disabled=true;const exportEpoch=epoch,scope={...active,snapshot};try{let after="",rows=[],expected=null;while(true){const data=await api({action:"summary",...scope,after});if(epoch!==exportEpoch)throw Error("การทำงานถูกยกเลิก");expected??=Number(data.total_participants);rows.push(...data.rows);$("status").textContent="กำลังส่งออก "+rows.length+" / "+expected+" รหัส";if(data.rows.length<100)break;const next=data.rows.at(-1).participant_id;if(next===after)throw Error("อ่านหน้าถัดไปไม่สำเร็จ");after=next;}const lines=[["participant_id","assessment_count","activity_open_count","latest_score","latest_level","last_used_at_utc","filter_from_th","filter_to_th","snapshot_utc"],...rows.map(r=>[r.participant_id,r.assessment_count,r.activity_count,r.latest_score,r.latest_level,r.last_used_at,scope.from,scope.to,scope.snapshot])];const blob=new Blob(["\uFEFF"+lines.map(r=>r.map(csvCell).join(",")).join("\r\n")],{type:"text/csv;charset=utf-8"});const url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download="research-summary-"+new Date().toISOString().slice(0,10)+".csv";link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);$("status").textContent="ส่งออกครบ "+rows.length+" รหัส";}catch(e){$("status").textContent="ส่งออกไม่สำเร็จ: "+e.message;}finally{exporting=false;if(token)$("export").disabled=!total;}};
function openDetail(id){detailId=id;kind="assessments";offset=0;$("detail").hidden=false;$("detailTitle").textContent="ประวัติ · "+id;$("detailTitle").focus();void loadHistory();}
async function loadHistory(){const seq=++detailRequest;$("detailStatus").textContent="กำลังอ่านประวัติ…";$("historyRows").replaceChildren();$("historyPrev").disabled=$("historyNext").disabled=true;const scores=kind==="assessments";$("showAssessments").className=scores?"":"secondary";$("showActivities").className=scores?"secondary":"";$("historyHead").replaceChildren();const hr=document.createElement("tr");for(const title of (scores?["วันที่","คะแนน","ระดับ"]:["วันที่","กิจกรรม","เหตุการณ์"])){const th=document.createElement("th");th.scope="col";th.textContent=title;hr.append(th);}$("historyHead").append(hr);try{const data=await api({action:"history",...active,snapshot,participant_id:detailId,kind,offset});if(seq!==detailRequest)return;for(const item of data.rows){const row=document.createElement("tr");cell(row,time(scores?item.assessed_at:item.used_at));cell(row,scores?item.score:item.activity_name);cell(row,scores?item.stress_level:({opened:"กดเปิด",completed_self_report:"ยืนยันทำเสร็จ (ผู้ใช้รายงาน)"}[item.event_type]||"ข้อมูลเก่า / ไม่ระบุประเภท"));$("historyRows").append(row);}$("detailStatus").textContent=data.rows.length?"":"ไม่มีประวัติในช่วงนี้";$("historyPage").textContent="หน้า "+(offset/50+1)+" · "+data.total+" รายการ";$("historyPrev").disabled=offset===0;$("historyNext").disabled=offset+data.rows.length>=data.total;}catch(e){if(seq===detailRequest)$("detailStatus").textContent=e.message;}}
$("showAssessments").onclick=()=>{kind="assessments";offset=0;void loadHistory();};$("showActivities").onclick=()=>{kind="activities";offset=0;void loadHistory();};$("historyPrev").onclick=()=>{offset=Math.max(0,offset-50);void loadHistory();};$("historyNext").onclick=()=>{offset+=50;void loadHistory();};$("closeDetail").onclick=()=>{detailRequest++;$("detail").hidden=true;};
